name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Optional validation steps
      - name: Validate HTML
        run: |
          npm install -g html-validate
          html-validate index.html --config .github/html-validate-config.json || echo "HTML validation completed with warnings"

      - name: Check Links
        run: |
          npm install -g markdown-link-check
          markdown-link-check README.md --config .github/link-check-config.json || echo "Link check completed with warnings"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: public  # public not . (root) folder containing index.html
          exclude_assets: '.github'
          enable_jekyll: false
